#!/bin/bash -e

# updates hashes in the following files:
# - ./run_once_0-posix-sync.sh
# - ./run_once_1-install-vscode-ext.sh
# - ./run_once_99-run-krr.sh

# Generated by an AI assistant developed by Perplexity AI (model: GPT-5.2).
# Purpose: Updates a file line matching "^# DEP_HASH:" to "# DEP_HASH:<new_hash>" using awk.
update_dep_hash() {
	local dep_hash="$1"
	local file="$2"

	awk -v dep="$dep_hash" '
    /^# DEP_HASH:/ { print "# DEP_HASH:" dep; next }
    { print }
  ' "$file" >"$file.tmp" && mv -- "$file.tmp" "$file"
}
