#!/bin/bash -e

# =+= EXAMPLE (plaintext: `abc`)
# DEP_HASH:edeaaff3f1774ad2888673770c6d64097e391bc362d7d6fb34982ddf0efd18cb
# =+= END EXAMPLE

# Generated by an AI assistant developed by Perplexity AI (model: GPT-5.2).
# Purpose: Updates a file line matching "^# DEP_HASH:" to "# DEP_HASH:<new_hash>" using awk.
update_dep_hash() {
  local dep_hash="$1"
  local file="$2"

  awk -v dep="$dep_hash" '
    /^# DEP_HASH:/ { print "# DEP_HASH:" dep; next }
    { print }
  ' "$file" >"$file.tmp" && mv -- "$file.tmp" "$file"

  chmod +x "$file"
}

# Hand-written.
# Does what it says on the tin.
aggregate_hash_folder() {
  find "$@" -type f -print0 | sort -z | xargs -0 sha256sum | sha256sum | head -c 64
}

# - ./run_once_0-posix-sync.sh
update_dep_hash "$(head -c 1000 /dev/random | sha256sum | head -c 64)" "./.chezmoiscripts/posix/run_once_0-posix-sync.sh"

# - ./run_once_1-install-vscode-ext.sh
update_dep_hash "$(sha256sum dot_vscode-extensions.txt | head -c 64)" "./.chezmoiscripts/posix/run_once_1-install-vscode-ext.sh"

# - ./run_once_99-run-krr.sh
# update_dep_hash "$(aggregate_hash_folder dot_config/nvim dot_config/kmr)" "./.chezmoiscripts/posix/run_once_99-run-krr.sh"
