# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 Claude Sonnet 4.6 (Anthropic)
#
# Generated by Claude Sonnet 4.6, an AI assistant by Anthropic.
# Licensed under the Apache License, Version 2.0. You may obtain a copy at
# https://www.apache.org/licenses/LICENSE-2.0

_watcher_pid=""
_watcher_dir=""

_autowatch() {
  # Kill existing watcher if we've left its project tree
  if [[ -n "$_watcher_pid" ]] && [[ "$PWD" != "$_watcher_dir"* ]]; then
    kill "$_watcher_pid" 2>/dev/null
    _watcher_pid=""
    _watcher_dir=""
    echo "info: watcher stopped" >&2
  fi

  # Warn if a .watchrc exists but we're outside ~/repositories
  if [[ -f "$PWD/.watchrc" ]] && [[ "$PWD" != "$HOME/repositories"* ]]; then
    echo "warning: .watchrc found in $PWD but is outside ~/repositories, ignoring" >&2
    return
  fi

  # Only proceed if we're somewhere inside ~/repositories
  [[ "$PWD" != "$HOME/repositories"* ]] && return

  # Only proceed if a .watchrc exists and no watcher is already running
  [[ -f "$PWD/.watchrc" ]] && [[ -z "$_watcher_pid" ]] || return

  local WATCH_CMD=""
  source "$PWD/.watchrc"

  if [[ -n "$WATCH_CMD" ]]; then
    eval "$WATCH_CMD" &
    _watcher_pid=$!
    _watcher_dir="$PWD"
    echo "info: watcher started (PID $_watcher_pid): $WATCH_CMD" >&2
  fi
}

_autowatch_cleanup() {
  [[ -n "$_watcher_pid" ]] && kill "$_watcher_pid" 2>/dev/null
  echo "info: watcher stopped" >&2
}

autoload -U add-zsh-hook
add-zsh-hook chpwd _autowatch
add-zsh-hook zshexit _autowatch_cleanup

# Example .watchrc:
#
#   WATCH_CMD="rendercv render --watch Parker_Edward_Wahle_CV.yaml"
